# Generated by Django 3.2.10 on 2022-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histology',
            options={'verbose_name_plural': 'histology'},
        ),
        migrations.AlterField(
            model_name='histology',
            name='non_rejection_diagnosis',
            field=models.CharField(blank=True, choices=[('Normal biopsy or nonspecific changes', 'Normal biopsy or nonspecific changes'), ('inadequate for  assessment of rejection', 'inadequate for  assessment of rejection'), ('Rejection only-no additional pathological abnormalities', 'Rejection only-no additional pathological abnormalities'), ('other pathology', 'other pathology'), ('glomerular ischemia', 'glomerular ischemia'), ('infarction', 'infarction'), ('ATI: not otherwise specified', 'ATI: not otherwise specified'), ('ATI: suspicious for CNI toxicity', 'ATI: suspicious for CNI toxicity'), ('TMA: not otherwise specified', 'TMA: not otherwise specified'), ('TMA: acute glomerular involvement', 'TMA: acute glomerular involvement on LM'), ('TMA: subacute/chronic glomerular involvement on LM', 'TMA: subacute/chronic glomerular involvement on LM'), ('TMA: acute arteriolar/arterial involvement', 'TMA: acute arteriolar/arterial involvement on LM'), ('TMA: subacute/chronic arteriolar/arterial involvement on LM', 'TMA: subacute/chronic arteriolar/arterial involvement on LM'), ('TMA: EM features only', 'TMA: EM features only'), ('IFTA: NOS', 'IFTA: not otherwise specified'), ('IFTA1: Mild', 'IFTA1: Mild'), ('IFTA2: Moderate', 'IFTA2: Moderate'), ('IFTA3: Severe', 'IFTA3: Severe'), ('Significant vascular pathology', 'Significant vascular pathology'), ('Significant arterial intimal thickening', 'Significant arterial intimal thickening'), ('arterial intimal fibrosis (non-inflammatory)', 'Arterial intimal fibrosis (non-inflammatory)'), ('arterial intimal thickening without fibroelastosis', 'Arterial intimal thickening without fibroelastosis (at least partially)'), ('significant arteriolar hyalinosis', 'significant arteriolar hyalinosis'), ('significant arteriolar hyalinosis-likely donor-derived', 'significant arteriolar hyalinosis-likely donor-derived'), ('significant arteriolar hyalinosis - suspicious for CNI toxicity', 'significant arteriolar hyalinosis - suspicious for CNI toxicity'), ('infection: not otherwise specified', 'infection: not otherwise specified'), ('infection: neutrophilic pyelonephritis/Suspicious for pyelonephritis', 'infection: neutrophilic pyelonephritis/Suspicious for pyelonephritis'), ('infection: BK virus nephropathy', 'infection: BK virus nephropathy'), ('infection: granulomatous', 'infection: granulomatous'), ('Polyomavirus Nephropathy Class 1', 'Polyomavirus Nephropathy Class 1'), ('Polyomavirus Nephropathy Class 2', 'Polyomavirus Nephropathy Class 2'), ('Polyomavirus Nephropathy Class 3', 'Polyomavirus Nephropathy Class 3'), ('glomerular disease: not otherwise specified', 'Gd Nos'), ('glomerular disease: immune complex, not otherwise specified', 'immune complex, not otherwise specifie'), ('glomerular disease: immune complex, IgA', 'immune complex, IgA'), ('glomerular disease: immune complex, membranous', 'glomerular disease: immune complex, membranous'), ('glomerular disease: immune complex, Lupus nephritis', 'glomerular disease: immune complex, Lupus nephritis'), ('glomerular disease: C3 glomerulopathy', 'C3 glomerulopathy'), ('glomerular disease: FSGS', 'FSGS'), ('glomerular disease: FSGS, likely recurrent', 'FSGS, likely recurrent'), ('glomerular disease: diabetic change', 'glomerular disease: diabetic change'), ('glomerular disease: paraprotein-related', 'glomerular disease: paraprotein-related'), ('tubulointerstitial disease: not otherwise specified', 'tubulointerstitial disease'), ('tubulointerstitial disease: granulomatous TIN', 'tubulointerstitial disease: granulomatous TIN'), ('tubulointerstitial disease: drug-induced TIN', 'tubulointerstitial disease: drug-induced TIN'), ('neoplasia: not otherwise specified', 'neoplasia'), ('preneoplasia/suspicious for neoplasia', 'preneoplasia/suspicious for neoplasia'), ('post-transplant lymphoproliferative disease', 'post-transplant lymphoproliferative disease')], max_length=200, verbose_name='non-rejection diagnosis'),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('living donor', 'living donor'), ('deceased donor', 'deceased donor')], max_length=100),
        ),
    ]
