# Generated by Django 3.2.10 on 2022-10-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0002_auto_20220919_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencingdata',
            old_name='run_date',
            new_name='sequencing_date',
        ),
    ]
