# Generated by Django 3.2.10 on 2023-07-13 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0003_rename_run_date_sequencingdata_sequencing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histology',
            name='crescents',
        ),
        migrations.RemoveField(
            model_name='sequencingdata',
            name='rna_storage',
        ),
        migrations.RemoveField(
            model_name='transplant',
            name='dgf_time',
        ),
        migrations.RemoveField(
            model_name='transplant',
            name='dgf_time_units',
        ),
        migrations.AddField(
            model_name='histology',
            name='crescent_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% of glomeruli with crescents (extracapillary proliferation)'),
        ),
        migrations.AddField(
            model_name='sequencingdata',
            name='machine_type',
            field=models.CharField(blank=True, choices=[('max/flex', 'max/flex'), ('sprint', 'sprint')], max_length=50),
        ),
        migrations.AddField(
            model_name='sequencingdata',
            name='tissue_fixation',
            field=models.CharField(choices=[('FFPE', 'FFPE'), ('RNAlater', 'RNAlater'), ('frozen', 'frozen')], default='FFPE', max_length=100, verbose_name='tissue storage'),
        ),
        migrations.AddField(
            model_name='transplant',
            name='donor_cmv_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='cytomegalovirus status'),
        ),
        migrations.AddField(
            model_name='transplant',
            name='donor_ebv_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Epstein-Barr virus status'),
        ),
        migrations.AddField(
            model_name='transplant',
            name='donor_hcv_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='hepatitus C status'),
        ),
        migrations.AddField(
            model_name='transplant',
            name='donor_hiv_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='HIV status'),
        ),
        migrations.AddField(
            model_name='transplant',
            name='recipient_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='recipient age (years)'),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='dd_cf_dna',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='donor-derived cf-DNA (%)'),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='immunosuppressant_dose_units',
            field=models.CharField(blank=True, choices=[('mg/day', 'mg/day'), ('mg twice per day', 'mg twice per day'), ('mg per week', 'mg per week'), ('mg per 15 days', 'mg per 15 days')], max_length=100, verbose_name='immunosuppresant dose units'),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='immunosuppressant_trough',
            field=models.FloatField(blank=True, null=True, verbose_name='immunosuppressant trough level:C0 (ng/mL)'),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='immunosuppressants',
            field=models.CharField(blank=True, choices=[('abatacept', 'abatacept'), ('azathioprine', 'azathioprine'), ('belatacept', 'belatacept'), ('cyclosporine', 'cyclosporine'), ('everolimus', 'everolimus'), ('IDeS', 'imlifidase (IDeS)'), ('MMF', 'mycophenolate mofetil (MMF)'), ('MPA', 'mycophenolic acid (MPA)'), ('prednisone', 'prednisone'), ('sirolimus', 'sirolimus'), ('tacrolimus', 'tacrolimus'), ('other', 'other')], max_length=100, verbose_name='immunosuppresants'),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='non_anti_hla_dsa_type',
            field=models.CharField(blank=True, choices=[('AT1R', 'AT1R'), ('MICA', 'MICA'), ('ECXM', 'ECXM'), ('vimentin', 'vimentin'), ('collagen', 'collagen'), ('K-a-1', 'K-a-1'), ('tubulin', 'tubulin'), ('other', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='prot_creat_ratio',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)], verbose_name='protein/creatinine ratio'),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='rejection_treatment',
            field=models.CharField(blank=True, choices=[('alemtuzumab', 'alemtuzumab'), ('bortezomib', 'bortezomib'), ('ATG', 'anti-thymocyte globulin (ATG)'), ('eculizumab', 'eculizumab'), ('IVIG', 'intravenous immunoglobulin (IVIG)'), ('plasmapharesis', 'plasmapharesis'), ('rituximab', 'rituximab')], max_length=100, verbose_name='rejection treatment'),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='treatment_response',
            field=models.CharField(blank=True, choices=[('complete', 'Complete response (Cr within 10% of baseline)'), ('partial', 'Partial response (Cr 10-50% over baseline) '), ('none', 'no response (Cr >50% increase over baseline)')], max_length=100, verbose_name='rejection treatment response'),
        ),
        migrations.AlterField(
            model_name='histology',
            name='cg_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='glomerular basement membrane double contours (cg)'),
        ),
        migrations.AlterField(
            model_name='histology',
            name='clinical_biopsy_indication',
            field=models.CharField(blank=True, choices=[('protocol', 'protocol'), ('DGF', 'Delayed Graft Function'), ('slow deterioration', 'slow deterioration (progressive increase in serum creatinine over time)'), ('ARF', 'Acute Renal Failure'), ('proteinuria', 'proteinuria'), ('hematuria', 'hematuria'), ('SUSP AR', 'Suspicious for acute rejection'), ('SUSP PVN', 'Suspicious for Polyoma Virus Nephropathy'), ('Transplantectomy', 'Transplantectomy biopsy'), ('de novo DSA', 'de novo DSA'), ('follow-up', 'follow-up from previous biopsy'), ('other', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='histology',
            name='cv_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='vascular fibrous intimal thickening (cv)'),
        ),
        migrations.AlterField(
            model_name='histology',
            name='fsgs_type',
            field=models.CharField(blank=True, choices=[('cellular', 'cellular'), ('collapsing', 'collapsing'), ('NOS', 'not otherwise specified (NOS)'), ('perihiliar', 'perihiliar'), ('tip', 'tip')], max_length=100, verbose_name='FSGS type'),
        ),
        migrations.AlterField(
            model_name='histology',
            name='non_rejection_diagnosis',
            field=models.CharField(blank=True, choices=[('normal', 'normal biopsy or nonspecific changes'), ('inadequate', 'inadequate for  assessment of rejection'), ('rejection only', 'Rejection only-no additional pathological abnormalities'), ('other', 'other pathology'), ('glomerular ischemia', 'glomerular ischemia'), ('infarction', 'infarction'), ('ATI', 'ATI: not otherwise specified'), ('ATI suspicious for CNIT', 'ATI suspicious for CNI toxicity'), ('TMA NOS', 'TMA: not otherwise specified'), ('acute glomerular TMA', 'TMA: acute glomerular involvement on LM'), ('subacute/chronic glomerular TMA', 'TMA: subacute/chronic glomerular involvement on LM'), ('acute arteriolar/arterial TMA', 'TMA: acute arteriolar/arterial involvement on LM'), ('subacute/chronic arteriolar/arterial TMA', 'TMA: subacute/chronic arteriolar/arterial involvement on LM'), ('TMA EM features only', 'TMA: EM features only'), ('IFTA NOS', 'IFTA: not otherwise specified'), ('IFTA1', 'IFTA1: Mild'), ('IFTA2', 'IFTA2: Moderate'), ('IFTA3', 'IFTA3: Severe'), ('significant vascular pathology', 'Significant vascular pathology'), ('significant arterial intimal thickening', 'Significant arterial intimal thickening'), ('arterial intimal fibrosis (non-inflammatory)', 'Arterial intimal fibrosis (non-inflammatory)'), ('arterial intimal thickening without fibroelastosis', 'Arterial intimal thickening without fibroelastosis (at least partially)'), ('significant arteriolar hyalinosis', 'significant arteriolar hyalinosis'), ('significant arteriolar hyalinosis likely donor-derived', 'significant arteriolar hyalinosis likely donor-derived'), ('significant arteriolar hyalinosis suspicious for CNIT', 'significant arteriolar hyalinosis suspicious for CNI toxicity'), ('infection NOS', 'infection: not otherwise specified'), ('neutrophilic pyelonephritis/suspicious for pyelonephritis', 'infection: neutrophilic pyelonephritis/suspicious for pyelonephritis'), ('BKV', 'infection: BK virus nephropathy'), ('GIN', 'granulomatous interstitial nephritis (GIN)'), ('PVN class 1', 'Polyomavirus Nephropathy Class 1'), ('PVN class 2', 'Polyomavirus Nephropathy Class 2'), ('PVN class 3', 'Polyomavirus Nephropathy Class 3'), ('glomerular disease NOS', 'glomerular disease: not otherwise specified'), ('immune complex glomerular disease', 'immune complex glomerular disease not otherwise specified'), ('immune complex IgA glomerular disease', 'immune complex IgA glomerular disease'), ('IgA nephropathy', 'glomerular disease: IgA nephropathy'), ('immune complex membranous glomerular disease', 'glomerular disease: immune complex, membranous'), ('lupus nephritis', 'immune complex glomerular disease: lupus nephritis'), ('C3 glomerulopathy', 'glomerular disease: C3 glomerulopathy'), ('FSGS', 'glomerular disease: FSGS'), ('recurrent FSGS', 'recurrent FSGS'), ('diabetic change', 'glomerular disease: diabetic change'), ('paraprotein-related', 'paraprotein-related glomerular disease'), ('tubulointerstitial disease NOS', 'tubulointerstitial disease not otherwise specified'), ('granulomatous TIN', 'tubulointerstitial disease: granulomatous TIN'), ('drug-induced TIN', 'tubulointerstitial disease: drug-induced TIN'), ('neoplasia NOS', 'neoplasia not otherwise specified'), ('preneoplasia/suspicious for neoplasia', 'preneoplasia/suspicious for neoplasia'), ('PTLD', 'post-transplant lymphoproliferative disease (PTLD)')], max_length=200, verbose_name='non-rejection diagnosis'),
        ),
        migrations.AlterField(
            model_name='histology',
            name='principal_diagnosis',
            field=models.CharField(blank=True, choices=[('inadequate', 'inadequate for diagnosis'), ('normal', 'normal'), ('NER', 'no evidence of rejection (NER)'), ('active AMR', 'active AMR'), ('chronic active AMR', 'chronic active AMR'), ('chronic AMR', 'chronic AMR'), ('acute TCMR', 'acute TCMR'), ('mixed rejection', 'mixed rejection'), ('chronic active TCMR', 'chronic active TCMR'), ('Borderline TCMR', 'Borderline/Suspicious for acute TCMR'), ('C4dNER', 'C4d with no evidence of rejection'), ('PVN', 'polyomavirus nephropathy'), ('CNIT', 'CNI toxicity (CNIT)'), ('recurrent glomerulonephritis', 'recurrent glomerulonephritis'), ('de novo glomerulonephritis', 'de novo glomerulonephritis'), ('ATI', 'acute tubular injury (ATI)'), ('donor disease', 'donor disease'), ('IFTA NOS', 'IFTA not otherwise specified'), ('arteriosclerosis', 'arteriosclerosis')], max_length=200, verbose_name='principal diagnosis'),
        ),
        migrations.AlterField(
            model_name='histology',
            name='ptcml',
            field=models.CharField(blank=True, choices=[('normal', 'normal (<3 layers)'), ('moderate ', '3-6 layers'), ('severe', '≥7 layers in one cortical PTC and ≥5 layers in two additional capillaries')], max_length=100, verbose_name='peritubular capillary basement membrane multilayering (PTCML)'),
        ),
        migrations.AlterField(
            model_name='histology',
            name='rejection_diagnosis',
            field=models.CharField(blank=True, choices=[('NER', 'no evidence of rejection (NER)'), ('inadequate', 'inadequate for assessment of rejection'), ('mixed rejection', 'mixed rejection'), ('active AMR', 'active AMR'), ('chronic active AMR', 'chronic active AMR'), ('chronic AMR', 'chronic AMR'), ('C4d NER', 'C4D deposition without morphologic evidence for active rejection'), ('Borderline TCMR', 'Borderline/Suspicious for acute TCMR'), ('acute TCMR', 'acute TCMR'), ('chronic active TCMR', 'chronic active TCMR'), ('acute TCMR IA', 'acute TCMR IA'), ('acute TCMR IB', 'acute TCMR IB'), ('acute TCMR IIA', 'acute TCMR IIA'), ('acute TCMR IIB', 'acute TCMR IIB'), ('acute TCMR III', 'acute TCMR III'), ('chronic active TCMR IA', 'chronic active TCMR IA'), ('chronic active TCMR IB', 'chronic active TCMR IB'), ('chronic active TCMR II', 'chronic active TCMR II')], max_length=200, verbose_name='rejection diagnosis'),
        ),
        migrations.AlterField(
            model_name='histology',
            name='tissue_technique',
            field=models.CharField(blank=True, choices=[('frozen', 'frozen'), ('paraffin', 'paraffin'), ('AFA', 'acidified formal alcohol (AFA)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='file_ref',
            field=models.CharField(blank=True, help_text='<b>This is the name that will be stored in the database for your RCC file.</b><br/>This reference will be matched against files that are uploaded as batches.<br/>You can also upload a file directly and it will be associated to this reference.', max_length=256, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='deceased_donor_type',
            field=models.CharField(blank=True, choices=[('DBD', 'donation after brain death (DBD)'), ('DCD', 'donation after circulatory death (DCD)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='delayed_graft_function',
            field=models.BooleanField(blank=True, null=True, verbose_name='delayed graft function (DGF)'),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='donor_criteria',
            field=models.CharField(blank=True, choices=[('SCD', 'Standard Donor Criteria (SCD)'), ('ECD', 'Expanded Donor Criteria (ECD)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='donor_sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='induction_therapy',
            field=models.CharField(blank=True, choices=[('ATG', 'thymoglbulin (ATG)'), ('basiliximab', 'basiliximab'), ('none', 'none')], max_length=100, verbose_name='induction therapy'),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='living_donor_type',
            field=models.CharField(blank=True, choices=[('unrelated', 'unrelated donor'), ('related HLA identical', 'related HLA identical donor'), ('related non-HLA identical', 'related non-HLA identical donor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='primary_kidney_disease',
            field=models.CharField(blank=True, choices=[('amyloidosis', 'amyloidosis'), ('ANCA vasculitis', 'anti-neutrophil cytoplasmic autoantibody (ANCA) vasculitis'), ('CAKUT', 'congenital abnormality of the kidney or urinary tract (CAKUT)'), ('CPN', 'chronic progressive nephropathy (CPN)'), ('complement 3 glomerulopathy', 'complement 3 glomerulopathy'), ('diabetes mellitus', 'diabetes mellitus'), ('diabetic nephropathy', 'diabetic nephropathy'), ('FSGS', 'focal segmental glomerulosclerosis (FSGS)'), ('glomerular nephropathy', 'glomerular nephropathy'), ('hypertensive kidney disease', 'hypertensive kidney disease'), ('IgA nephropathy', 'IgA nephropathy'), ('interstitial nephropathy/pyelonephritis', 'interstitial nephropathy/pyelonephritis'), ('MPGN', 'Membranoproliferative glomerulonephritis (MPGN)'), ('MIDD', 'Monoclonal immunoglobulin (Ig) deposition disease (MIDD)'), ('vascular nephropathy', 'vascular nephropathy'), ('alport syndrome', 'alport syndrome'), ('fabry disease', 'fabry disease'), ('polycystic kidney disease', 'polycystic kidney disease'), ('congenital nephropathy', 'congenital nephropathy')], max_length=200, verbose_name='primary kidney disease'),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='recipient_height_units',
            field=models.CharField(choices=[('cm', 'centimeters (cm)'), ('m', 'meters (m)'), ('in', 'inches (in)'), ('ft', 'feet (ft)')], default='cm', max_length=50),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='recipient_sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='recipient_weight_units',
            field=models.CharField(choices=[('kg', 'kilograms (kg)'), ('lbs', 'pounds (lb)')], default='kg', max_length=50),
        ),
    ]
