name: Build and push image

env:
  REGISTRY: ghcr.io
  CONTAINER_NAME: paristxgroup/icdot_production_histomx

on:
  push:
    branches: [ "main" ]
    paths: [ "histomx/**", "compose/production/histomx/**", "compose/local/histomx/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - uses: docker/login-action@v2
        name: Login to repository
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        name: Build and push histomx
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:latest,${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          context: .
          file: ./compose/production/histomx/Dockerfile
